import type { Idl } from '@coral-xyz/anchor';
import { instructionDiscriminator } from '../orca/anchor-idl-orca';

export const MAGIC_EDEN_PROGRAM_ID = 'MEisE1HzehtrDpAAT8PnLHjpSSkRYakotTuJRPjTpo8';

// Minimal Anchor-compatible IDL for the Magic Eden v2 auction house program.
// On-chain binary layouts may deviate from pure Anchor on some instruction variants;
// all decoded results carry confidence: 'low' and a decoder warning.
export const MAGIC_EDEN_IDL: Idl = {
  metadata: {
    name: 'magic_eden',
    version: '0.1.0',
    spec: '0.1.0',
  },
  address: MAGIC_EDEN_PROGRAM_ID,
  instructions: [
    {
      name: 'sell',
      discriminator: instructionDiscriminator('sell'),
      accounts: [
        { name: 'wallet' },
        { name: 'token_account' },
        { name: 'metadata' },
        { name: 'authority' },
        { name: 'auction_house' },
        { name: 'auction_house_fee_account' },
        { name: 'seller_trade_state' },
        { name: 'free_seller_trade_state' },
        { name: 'token_program' },
        { name: 'system_program' },
        { name: 'program_as_signer' },
        { name: 'rent' },
      ],
      args: [
        { name: 'trade_state_bump', type: 'u8' },
        { name: 'free_trade_state_bump', type: 'u8' },
        { name: 'program_as_signer_bump', type: 'u8' },
        { name: 'buyer_price', type: 'u64' },
        { name: 'token_size', type: 'u64' },
      ],
    },
    {
      name: 'buy',
      discriminator: instructionDiscriminator('buy'),
      accounts: [
        { name: 'wallet' },
        { name: 'payment_account' },
        { name: 'transfer_authority' },
        { name: 'treasury_mint' },
        { name: 'token_account' },
        { name: 'metadata' },
        { name: 'escrow_payment_account' },
        { name: 'authority' },
        { name: 'auction_house' },
        { name: 'auction_house_fee_account' },
        { name: 'buyer_trade_state' },
        { name: 'token_program' },
        { name: 'system_program' },
        { name: 'rent' },
      ],
      args: [
        { name: 'trade_state_bump', type: 'u8' },
        { name: 'escrow_payment_bump', type: 'u8' },
        { name: 'buyer_price', type: 'u64' },
        { name: 'token_size', type: 'u64' },
      ],
    },
    {
      name: 'execute_sale',
      discriminator: instructionDiscriminator('execute_sale'),
      accounts: [
        { name: 'buyer' },
        { name: 'seller' },
        { name: 'token_account' },
        { name: 'token_mint' },
        { name: 'metadata' },
        { name: 'treasury_mint' },
        { name: 'escrow_payment_account' },
        { name: 'seller_payment_receipt_account' },
        { name: 'buyer_receipt_token_account' },
        { name: 'authority' },
        { name: 'auction_house' },
        { name: 'auction_house_fee_account' },
        { name: 'auction_house_treasury' },
        { name: 'buyer_trade_state' },
        { name: 'seller_trade_state' },
        { name: 'free_trade_state' },
        { name: 'token_program' },
        { name: 'system_program' },
        { name: 'ata_program' },
        { name: 'program_as_signer' },
        { name: 'rent' },
      ],
      args: [
        { name: 'escrow_payment_bump', type: 'u8' },
        { name: 'free_trade_state_bump', type: 'u8' },
        { name: 'program_as_signer_bump', type: 'u8' },
        { name: 'buyer_price', type: 'u64' },
        { name: 'token_size', type: 'u64' },
      ],
    },
    {
      name: 'cancel',
      discriminator: instructionDiscriminator('cancel'),
      accounts: [
        { name: 'wallet' },
        { name: 'token_account' },
        { name: 'token_mint' },
        { name: 'authority' },
        { name: 'auction_house' },
        { name: 'auction_house_fee_account' },
        { name: 'trade_state' },
        { name: 'token_program' },
        { name: 'system_program' },
      ],
      args: [
        { name: 'buyer_price', type: 'u64' },
        { name: 'token_size', type: 'u64' },
      ],
    },
    {
      name: 'deposit',
      discriminator: instructionDiscriminator('deposit'),
      accounts: [
        { name: 'wallet' },
        { name: 'payment_account' },
        { name: 'transfer_authority' },
        { name: 'escrow_payment_account' },
        { name: 'treasury_mint' },
        { name: 'authority' },
        { name: 'auction_house' },
        { name: 'auction_house_fee_account' },
        { name: 'token_program' },
        { name: 'system_program' },
        { name: 'rent' },
      ],
      args: [
        { name: 'escrow_payment_bump', type: 'u8' },
        { name: 'amount', type: 'u64' },
      ],
    },
    {
      name: 'withdraw',
      discriminator: instructionDiscriminator('withdraw'),
      accounts: [
        { name: 'wallet' },
        { name: 'receipt_account' },
        { name: 'escrow_payment_account' },
        { name: 'treasury_mint' },
        { name: 'authority' },
        { name: 'auction_house' },
        { name: 'auction_house_fee_account' },
        { name: 'token_program' },
        { name: 'system_program' },
        { name: 'ata_program' },
        { name: 'rent' },
      ],
      args: [
        { name: 'escrow_payment_bump', type: 'u8' },
        { name: 'amount', type: 'u64' },
      ],
    },
  ],
  accounts: [],
  types: [],
  errors: [],
};
